# Generated by Django 5.0.2 on 2024-03-15 13:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('numero', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('complemento', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('bairro', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('cidade', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('estado', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='CEP inválido', regex='^\\d{8}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('mae', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('pai', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone inválido', regex='^\\d{10,15}$')])),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='CPF inválido', regex='^\\d{11}$')])),
                ('enderecos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.endereco')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrada', models.BooleanField()),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pessoa')),
            ],
        ),
    ]
